# This config is used for the CI workflow.
# Feel free to also use it locally for fast builds if you have the required setup!

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

# compile deps with llvm still for runtime perf
[profile.dev.package."*"]
codegen-backend = "llvm"

# Disable cranelift for release profile
[profile.release]
codegen-backend = "llvm"

# cranelift cannot build wasm32-unknown-unknown out of the box
[profile.web]
codegen-backend = "llvm"

[target.wasm32-unknown-unknown]
# Clang does not support wasm32-unknown-unknown,
# so we cannot use mold either: https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable/issues/168
linker = "lld"
rustflags = [
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]
rustdocflags = [
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]


[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # Mold linker
    "-Clink-arg=-fuse-ld=mold",
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]
rustdocflags = [
    # Mold linker
    "-Clink-arg=-fuse-ld=mold",
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
]
